###


###

GET http://localhost:8081/businesses
Accept: application/json
###
GET http://localhost:8081/get_all_order
Accept: application/json

###
POST http://localhost:8081/create_order
Content-Type: application/json

{
    "bid": 1,
    "cid": 1,
    "price": 10.0,
    "date": "2016-01-25T21:34:55",
    "waiting_time": "30",
    "pax": 5,
    "order_status":1,
    "payment_status": 1
    
}
###
POST http://localhost:8081/create_customer
Content-Type: application/json

{
    "name": "abc",
    "email": "abc@gmail.com",
    "phone_no": "12345678",
    "password": "goodpassword",
    "card_no": "122222222",
    "card_name": "card",
    "authorities": "ROLE_USER",
    "expiry_date": "2016-01-25T21:34:55"
}

###
GET http://localhost:8081/get_all_customers
