###


###

GET http://localhost:8081/business
Accept: application/json



### TESTING OF ORDERS
GET http://localhost:8081/get_all_order_business/1
Accept: application/json

###
POST http://localhost:8081/create_order/1/1
Content-Type: application/json

{

    "bid": 1,
    "cid": 1,
    "price": 10.0,
    "date": "2016-01-25T21:34:55",
    "pax": 5,
    "order_status":1,
    "payment_status": 1
    
}



### TESTING OF CUSTOMER
POST http://localhost:8081/create_customer
Content-Type: application/json

{
    "name": "abc",
    "email": "abc@gmail.com",
    "phone_no": "12345678",
    "password": "goodpassword",
    "card_no": "122222222",
    "card_name": "card",
    "authorities": "ROLE_USER",
    "expiry_date": "2016-01-25T21:34:55"
}

###
GET http://localhost:8081/get_all_customers



### TESTING OF BUSINESS
GET http://localhost:8081/business
Accept: application/json

###

GET http://localhost:8081/business/bid/1
Accept: application/json
###

GET http://localhost:8081/business/uen/ps123
Accept: application/json

###

GET http://localhost:8081/business/mid/0

### 
POST http://localhost:8081/business
content-type: application/json

{
    "uen": "123hs7",
    "name": "hong seng", 
    "password": "goodpassword",
    "contact_number": "9330",
    "mid": 0,
    "authorities": "ROLE_USER",
    "waiting_time": 0,
    "website": "hello"
}


###
GET http://localhost:8081/users/login/abc@gmail.com/goodpassword

###
GET http://localhost:8081/business/login/123ab7/goodpassword


### TESTING OF ORDERS IN QUEUE
GET http://localhost:8081/business/bid/1/status/0
Content-Type: application/json

###
GET http://localhost:8081/business/bid/1/status/1
Content-Type: application/json

###
PUT http://localhost:8081/business/bid/1/oid/26
Content-Type: application/json

###
DELETE HTTP://localhost:8081/business/bid/1/oid/26
Content-Type: application/json



### TESTING OF TABLES
GET http://localhost:8081/business/2/table
Content-Type: application/json

###
GET http://localhost:8081/business/2/table/2
Content-Type: application/json

###
PUT http://localhost:8081/business/table/2/free
Content-Type: application/json

###
PUT http://localhost:8081/business/table/2/occupy
Content-Type: application/json

### TESTING WAITING TIME
GET http://localhost:8081/business/1/type/5/waiting_time
Content-Type: application/json

###
GET http://localhost:8081/get_all_order_business/1
Accept: application/json

###
PUT http://localhost:8081/business/bid/1/type/5/add_time/5
Content-Type: application/json