###


###

GET http://localhost:8081/businesses
Accept: application/json

###

GET http://localhost:8081/get_all_order
Authorization: Basic abc@gmail.com goodpassword

###
POST http://localhost:8081/create_order
Content-Type: application/json

{
    "bid": "2",
    "cid": "1",
    "price": "10",
    "date": "2016-01-25T21:34:55",
    "pax": 2,
    "order_Status":1,
    "payment_status": 1
    
}
###
POST http://localhost:8081/create_customer
Content-Type: application/json

{
    "name": "abc",
    "email": "abc@gmail.com",
    "phone_no": "12345678",
    "password": "goodpassword",
    "card_no": "122222222",
    "card_name": "card",
    "expiry_date": "2016-01-25T21:34:55",
    "authorities": "ROLE_ADMIN"
}

###
GET http://localhost:8081/get_all_customers

###

GET http://localhost:8081/business
Accept: application/json

###

GET http://localhost:8081/business/uen/tp123
Accept: application/json

###

GET http://localhost:8081/business/mid/0
Accept: application/json


### 
POST http://localhost:8081/business
content-type: application/json

{

    "uen": "ps123", 
    "name": "pasta express", 
    "password": "goodpassword",
    "contact_number": "9330",
    "mid": 0

}